import logging
import os
from datetime import datetime, timezone
from pathlib import Path

from telegram.ext import ContextTypes

from src.config import BACKUP_DIR, OWNER_ID
from src.database import queries
from src.services.outline_api import get_vpn_client

logger = logging.getLogger(__name__)

BYTES_PER_GB = 1_000_000_000


def _status_tag(key, sold_keys: set[str]) -> str:
    used_up = bool(key.data_limit) and (key.used_bytes or 0) >= key.data_limit
    if used_up:
        return "USED_UP"
    if str(key.key_id) in sold_keys:
        return "SOLD"
    return "AVAILABLE"


def _usage_lines(key) -> tuple[str, str]:
    used_gb = (key.used_bytes or 0) / BYTES_PER_GB
    if key.data_limit:
        limit_gb = key.data_limit / BYTES_PER_GB
        available_gb = max(key.data_limit - (key.used_bytes or 0), 0) / BYTES_PER_GB
        return (
            f"{used_gb:.2f} GB / {limit_gb:.2f} GB",
            f"{available_gb:.2f} GB",
        )
    return (f"{used_gb:.2f} GB / Unlimited", "Unlimited")


def _backup_recipients() -> list[int]:
    return sorted(set([OWNER_ID, *queries.get_admins()]))


def generate_backup_file(kind: str) -> str:
    """Builds a detailed text backup from latest live server/key state and returns file path."""
    os.makedirs(BACKUP_DIR, exist_ok=True)

    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d_%H-%M-%S_UTC")
    filename = f"{kind}_backup_{timestamp}.txt"
    file_path = os.path.join(BACKUP_DIR, filename)

    servers = queries.get_servers()
    lines = [
        "OUTLINE MANAGER BACKUP",
        f"Type: {kind}",
        f"Generated UTC: {now.isoformat()}",
        f"Server count: {len(servers)}",
        "",
    ]

    if not servers:
        lines.append("No servers configured.")
    else:
        for alias in sorted(servers.keys()):
            server_data = servers[alias]
            lines.append(f"=== SERVER: {alias} ===")
            lines.append(f"API URL: {server_data['api_url']}")
            lines.append(f"CERT SHA256: {server_data['cert_sha256']}")
            max_keys = server_data.get("max_key_count", 0)
            lines.append(f"Configured Max Keys: {max_keys if max_keys > 0 else 'Unlimited'}")

            client = get_vpn_client(alias)
            if not client:
                lines.append("ERROR: Could not connect to server API.")
                lines.append("")
                continue

            try:
                keys = client.get_keys()
            except Exception as e:
                lines.append(f"ERROR: Failed to fetch keys ({e}).")
                lines.append("")
                continue

            sold_keys = queries.get_sold_keys(alias)
            key_creators = queries.get_key_creators(alias)

            lines.append(f"Current Keys: {len(keys)}")
            if not keys:
                lines.append("(No keys on this server)")
                lines.append("")
                continue

            lines.append("--- KEY DETAILS ---")
            for key in keys:
                key_id = str(key.key_id)
                creator_username = key_creators.get(key_id) or "unknown"
                usage, available = _usage_lines(key)
                lines.append(f"Key ID: {key_id}")
                lines.append(f"Name: {key.name or 'Unnamed'}")
                lines.append(f"Status: {_status_tag(key, sold_keys)}")
                lines.append(f"Generated By: @{creator_username}")
                lines.append(f"Usage: {usage}")
                lines.append(f"Available Usage: {available}")
                lines.append(f"Access URL: {key.access_url or 'N/A'}")
                lines.append("")

    Path(file_path).write_text("\n".join(lines), encoding="utf-8")
    return file_path


def get_latest_backup_file(kind: str) -> str | None:
    """Returns latest backup file path for given kind (manual/auto), if any."""
    backup_dir = Path(BACKUP_DIR)
    if not backup_dir.exists():
        return None

    pattern = f"{kind}_backup_*.txt"
    files = sorted(backup_dir.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    return str(files[0]) if files else None


async def run_auto_backup_job(context: ContextTypes.DEFAULT_TYPE):
    """Daily scheduled backup generator + sender."""
    recipients = _backup_recipients()
    if not recipients:
        return

    try:
        file_path = generate_backup_file("auto")
    except Exception as e:
        logger.error(f"Auto backup generation failed: {e}")
        return

    caption = "🗂️ Daily auto backup file"
    for user_id in recipients:
        try:
            with open(file_path, "rb") as backup_file:
                await context.bot.send_document(
                    chat_id=user_id,
                    document=backup_file,
                    filename=os.path.basename(file_path),
                    caption=caption,
                )
        except Exception as send_err:
            logger.warning(f"Failed sending auto backup to {user_id}: {send_err}")
